services:

  postgres:
    image: postgres:16
    container_name: socialhabits-db
    environment:
      POSTGRES_DB: tfm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 456789
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/socialhabits
    container_name: socialhabits-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tfm_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 456789

      FRONTEND_URL: http://localhost:3000

      RESEND_API_KEY: re_Uob9raZw_3WsJQA1D55WVgQ8Gn3sgkFyT
      RESEND_FROM: onboarding@resend.dev

      JWT_SECRET: 5jA8vL9xN2pQ7mK4sT1wY6zR3eF8uH0cB9dX2nM5qP7kL1vR
      JWT_EXPIRATION: 86400000

  frontend:
      build:
        context: ./frontend/react-tfm-habits
      container_name: socialhabits-front
      depends_on:
        - backend
      ports:
        - "3000:3000"
      environment:
        CHOKIDAR_USEPOLLING: "true"

volumes:
  postgres_data: