services:

  postgres:
    image: postgres:16
    container_name: socialhabits-db
    environment:
      POSTGRES_DB: tfm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 456789
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/socialhabits
    container_name: socialhabits-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tfm_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 456789

  frontend:
    build:
      context: ./frontend/react-tfm-habits
    container_name: socialhabits-front
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"

volumes:
  postgres_data: