spring.application.name=socialhabits
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=dmoronroces@gmail.com
spring.mail.password=wezqjztjccrfuuzx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=5jA8vL9xN2pQ7mK4sT1wY6zR3eF8uH0cB9dX2nM5qP7kL1vR
jwt.expiration=86400000

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

